name: mem
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_quill: ^9.3.11
  sqflite: 2.3.0
  image_picker: 0.8.7+1
  flutter_hooks: 0.20.0
  flutter_keyboard_visibility: 6.0.0
  http: 1.2.1
  intl: ^0.18.1
  google_fonts: ^6.2.1
  flutter_chat_ui: ^1.6.12
  flutter_chat_types: ^3.6.2
  share_plus: ^2.2.0
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.3
  pdf: ^3.10.0
  file_picker: 8.0.3
  flutter_pdfview: ^1.2.3
  open_file: ^3.2.1
  moor_flutter: ^4.1.0
  image_gallery_saver: any
  permission_handler: any
  cupertino_icons: ^1.0.6
  google_generative_ai: ^0.2.0
  screenshot: ^2.5.0
  webview_flutter: 2.0.13
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/NotoSansJP-Black.ttf

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Black.ttf
          weight: 700
